\section*{Datos Experimentales}\label{sec:Datos Experimentales}
\addcontentsline{toc}{section}{Datos Experimentales}
Virtual Pharma no posee la infraestructura para tener sus propios servidores. En tiempos pasados esto limitaría a la empresa de proveer servicios web. Sin embargo con el avance de la tecnología aparece una herramienta que permite a la empresa tener sus servidores en la nube. Esta herramienta se llama Amazon Web Service(AWS) y brinda diversos servicios como Base de Datos, Almacenamiento y Computación entre otros. En este capitulo se verán los tres principales servicios que usará Virtual Pharma para sus operaciones.
<<echo=F,results=tex>>=
library(xtable)
n<-c(1,2,3)
g<-c(9.78,9.8,9.8)
tabla <- data.frame(n,g)
xtable(tabla)
@